const stockExchanges = [
  {
    name: "New York Stock Exchange",
    symbol: "NYSE",
    country: "United States",
    countryISO: "US",
    city: "New York",
    timezone: "EST",
    currency: "USD",
    foundedYear: 1792,
  },
  {
    name: "NASDAQ",
    symbol: "NASDAQ",
    country: "United States",
    countryISO: "US",
    city: "New York",
    timezone: "EST",
    currency: "USD",
    foundedYear: 1971,
  },
  {
    name: "Toronto Stock Exchange",
    symbol: "TSX",
    country: "Canada",
    countryISO: "CA",
    city: "Toronto",
    timezone: "EST",
    currency: "CAD",
    foundedYear: 1852,
  },
  {
    name: "London Stock Exchange",
    symbol: "LSE",
    country: "United Kingdom",
    countryISO: "UK",
    city: "London",
    timezone: "GMT",
    currency: "GBP",
    foundedYear: 1801,
  },
  {
    name: "Deutsche Börse (Frankfurt Stock Exchange)",
    symbol: "FWB",
    country: "Germany",
    countryISO: "DE",
    city: "Frankfurt",
    timezone: "CET",
    currency: "EUR",
    foundedYear: 1585,
  },
  {
    name: "Euronext",
    symbol: "ENX",
    country: "Multi-country (Eurozone)",
    countryISO: "NL",
    city: "Amsterdam",
    timezone: "CET",
    currency: "EUR",
    foundedYear: 2000,
  },
  {
    name: "Bolsas y Mercados Españoles (BME)",
    symbol: "BME",
    country: "Spain",
    countryISO: "ES",
    city: "Madrid",
    timezone: "CET",
    currency: "EUR",
    foundedYear: 1831,
  },
  {
    name: "Swiss Exchange (SIX)",
    symbol: "SIX",
    country: "Switzerland",
    countryISO: "CH",
    city: "Zurich",
    timezone: "CET",
    currency: "CHF",
    foundedYear: 1850,
  },
  {
    name: "Borsa Italiana",
    symbol: "BIT",
    country: "Italy",
    countryISO: "IT",
    city: "Milan",
    timezone: "CET",
    currency: "EUR",
    foundedYear: 1808,
  },
  {
    name: "Tokyo Stock Exchange",
    symbol: "TSE",
    country: "Japan",
    countryISO: "JP",
    city: "Tokyo",
    timezone: "JST",
    currency: "JPY",
    foundedYear: 1878,
  },
  {
    name: "Shanghai Stock Exchange",
    symbol: "SSE",
    country: "China",
    countryISO: "CN",
    city: "Shanghai",
    timezone: "CST",
    currency: "CNY",
    foundedYear: 1990,
  },
  {
    name: "Hong Kong Stock Exchange",
    symbol: "HKEX",
    country: "Hong Kong",
    countryISO: "HK",
    city: "Hong Kong",
    timezone: "HKT",
    currency: "HKD",
    foundedYear: 1891,
  },
  {
    name: "National Stock Exchange of India",
    symbol: "NSE",
    country: "India",
    countryISO: "IN",
    city: "Mumbai",
    timezone: "IST",
    currency: "INR",
    foundedYear: 1992,
  },
  {
    name: "Bombay Stock Exchange",
    symbol: "BSE",
    country: "India",
    countryISO: "IN",
    city: "Mumbai",
    timezone: "IST",
    currency: "INR",
    foundedYear: 1875,
  },
  {
    name: "Australian Securities Exchange",
    symbol: "ASX",
    country: "Australia",
    countryISO: "AU",
    city: "Sydney",
    timezone: "AEST",
    currency: "AUD",
    foundedYear: 1987,
  },
  {
    name: "BM&F Bovespa (São Paulo Stock Exchange)",
    symbol: "B3",
    country: "Brazil",
    countryISO: "BR",
    city: "São Paulo",
    timezone: "BRT",
    currency: "BRL",
    foundedYear: 1890,
  },
  {
    name: "Johannesburg Stock Exchange",
    symbol: "JSE",
    country: "South Africa",
    countryISO: "KR",
    city: "Johannesburg",
    timezone: "SAST",
    currency: "ZAR",
    foundedYear: 1887,
  },
  {
    name: "Moscow Exchange",
    symbol: "MOEX",
    country: "Russia",
    countryISO: "RU",
    city: "Moscow",
    timezone: "MSK",
    currency: "RUB",
    foundedYear: 2011,
  },
  {
    name: "Korea Exchange",
    symbol: "KRX",
    country: "South Korea",
    countryISO: "KR",
    city: "Busan & Seoul",
    timezone: "KST",
    currency: "KRW",
    foundedYear: 2005,
  },
  {
    name: "Taiwan Stock Exchange",
    symbol: "TWSE",
    country: "Taiwan",
    countryISO: "TW",
    city: "Taipei",
    timezone: "CST",
    currency: "TWD",
    foundedYear: 1961,
  },
];

export function getAll() {
  return stockExchanges;
}

export function get(symbol) {
  symbol = symbol?.toUpperCase();
  return stockExchanges.find(
    (exchange) =>
      exchange.symbol.toUpperCase() === symbol ||
      symbol.includes(exchange.symbol.toUpperCase())
  );
}

export function getByCountry(isoCode) {
  return stockExchanges.filter((exchange) => exchange.countryISO === isoCode);
}
